import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";
import { MSWProvider } from "./_component/MSWComponent";

const inter = Inter({ subsets: ['latin'] })

if(process.env.NEXT_RUNTIME === 'nodejs' && process.env.NODE_ENV === 'production') {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { server } = require('@/src/mocks/http')
  server.listen()
} 

export const metadata: Metadata = {
  title: "Z-COM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={inter.className}>
      <MSWProvider>
        {children} 
      </MSWProvider>
      </body>
    </html>
  );
}
